# Generated by Django 5.2.1 on 2025-05-14 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main display title of the demo page.', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Must be unique. Auto-generated if left blank in admin.', max_length=220, unique=True)),
                ('page_meta_title', models.CharField(blank=True, help_text='SEO Title for the page.', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Meta Description for the page.', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO Meta Keywords for the page (comma-separated).', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Short description for display on cards or listings.', null=True)),
                ('image_url', models.URLField(blank=True, help_text='URL for a preview image for the demo card.', max_length=500, null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether this demo is publicly visible.')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this demo should be highlighted as featured.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for listings (lower numbers show first).')),
                ('demo_url_name', models.CharField(blank=True, help_text="Optional: Django URL name for a specific interactive demo view (e.g., 'demos:image_classifier').", max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DemoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_order', models.FloatField(default=1.0, help_text='Order of this section within the demo page (e.g., 1, 1.1, 2).')),
                ('section_title', models.CharField(blank=True, help_text='Title of this section (optional).', max_length=255, null=True)),
                ('section_content_markdown', models.TextField(blank=True, help_text='Main content of the section in Markdown format.', null=True)),
                ('code_language', models.CharField(blank=True, help_text='Programming language of the code snippet (e.g., python, html).', max_length=50, null=True)),
                ('code_snippet_title', models.CharField(blank=True, help_text='Title for the code snippet block (optional).', max_length=255, null=True)),
                ('code_snippet', models.TextField(blank=True, help_text='The code snippet itself.', null=True)),
                ('code_snippet_explanation', models.TextField(blank=True, help_text='Explanation for the code snippet or its output.', null=True)),
                ('demo', models.ForeignKey(help_text='The demo this section belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='demos.demo')),
            ],
            options={
                'ordering': ['demo', 'section_order'],
                'unique_together': {('demo', 'section_order')},
            },
        ),
    ]
